Write-Host "===================================================================="
Write-Host " Astra Monorepo Service Starter"
Write-Host "===================================================================="
Write-Host ""
Write-Host "IMPORTANT PREREQUISITES:"
Write-Host "1. Make sure your Redis server is running. Celery depends on it."
Write-Host "2. Ensure you have created and configured your .env files for:"
Write-Host "   - astra/"
Write-Host "   - ai-guru/backend/"
Write-Host "  (Based on the .env.example files if they exist)"
Write-Host "3. Make sure all dependencies are installed for each project:"
Write-Host "   - pip install -r requirements.txt (for each Python project)"
Write-Host "   - npm install (for the frontend project)"
Write-Host ""
Write-Host "This script will open a new window for each service."
Write-Host "Please keep them running."
Write-Host ""
Write-Host "Starting services..."
Write-Host ""

Write-Host "[1/5] Starting Astra Authentication (Flask on port 5000)..."
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location 'c:\Users\MAHAJAN ASHOK\OneDrive\Desktop\astra_monorepo\asta_authentication'; python app.py"

Write-Host "[2/5] Starting AI Guru Backend (FastAPI on port 8001)..."
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location 'c:\Users\MAHAJAN ASHOK\OneDrive\Desktop\astra_monorepo\ai-guru\backend'; python -m uvicorn main:app --port 8001"

Write-Host "[3/5] Starting AI Guru Frontend (React on port 3000)..."
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location 'c:\Users\MAHAJAN ASHOK\OneDrive\Desktop\astra_monorepo\ai-guru\frontend'; npm install; npm start"

Write-Host "[4/5] Starting Astra Platform (Django on port 8000)..."
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location 'c:\Users\MAHAJAN ASHOK\OneDrive\Desktop\astra_monorepo\astra'; python manage.py migrate; python manage.py runserver 8000"

Write-Host "[5/5] Starting Astra Celery Worker..."
Start-Process powershell -ArgumentList "-NoExit", "-Command", "Set-Location 'c:\Users\MAHAJAN ASHOK\OneDrive\Desktop\astra_monorepo\astra'; celery -A astralearn worker -l info"

Write-Host ""
Write-Host "===================================================================="
Write-Host " All services are starting up in separate windows."
Write-Host "===================================================================="
Write-Host ""
Write-Host "Please check the individual windows for status and errors."
Write-Host ""
Write-Host "Access the applications at:"
Write-Host "  - Astra Authentication: http://127.0.0.1:5000"
Write-Host "  - AI Guru Frontend:     http://localhost:3000"
Write-Host "  - Astra Platform:       http://127.0.0.1:8000"
Write-Host ""
Write-Host "This window will close in 15 seconds..."
Start-Sleep -Seconds 15