# Generated by Django 5.2.6 on 2025-09-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='example_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='simplified_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
