# Generated by Django 5.0.3 on 2025-10-26 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_moduleprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='tutor.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer_key', models.CharField(max_length=10)),
                ('question_type', models.CharField(default='mcq', max_length=20)),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_cases', models.JSONField(blank=True, null=True)),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tutor.coursetestsession')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('submitted_answers', models.JSONField()),
                ('score', models.FloatField()),
                ('percentage', models.FloatField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('test_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutor.coursetestsession')),
            ],
        ),
    ]
